### ISSUE TITLE
pod install,pod库下载失败

### ISSUE THREAD

**Issue by XIAODINGPA** [Meituan-Dianping/EasyMVVM#2]
![image](https://user-images.githubusercontent.com/28077025/58000674-09750a00-7b0c-11e9-8937-7ca42d289e46.png)
直接  pod 'EasyMVVM'和 pod 'EasyAction',pod库下载失败
pod 文件修改成这样,pod install 下载能成功,
pod 'EasyMVVM', :git => 'https://github.com/Meituan-Dianping/EasyMVVM.git', :branch => 'master'
 pod 'EasyAction', :git => 'https://github.com/Meituan-Dianping/EasyAction.git', :branch => 'master'

**Comment by ValiantCat** [comment]
pod repo uprate
